---
    
- name: "upgrade packages."
  become: true
  apt:
    upgrade: "yes"

- name: "update apt"
  become: yes
  become_method: sudo
  apt:
    update_cache: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["npm"]
    state: latest
    update_cache: yes

- name: "install n node version manager"
  become: true
  npm:
    name: n
    global: yes
    production: yes
    
- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present

- name: "install nodejs 13.8.0"
  become: yes
  shell: n 13.8.0

