---

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: "Installing Node Dependencies"
  shell: |
    cd ~/backend
    npm i
# - name: "Executing app with pm2"
#   shell: |
#     cd ~/backend/dist
#     pm2 stop default
#     pm2 start main.js
#   register: execute_node

- name: start app 
  become: yes
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start

- name: "start pm2 server"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu