---

- name: "Unarchive backend files"
  unarchive:
    src: artifact.tar.gz
    dest: ~/

- name: "Installing Node Dependencies"
  shell: |
    cd ~/
    npm i
- name: "Executing app with pm2"
  shell: |
    cd ~/
    pm2 stop default
    pm2 start main.js
  register: execute_node


- name: "start pm2 server"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu