---
- name: "Copy Backend file"
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unarchive backend file"
  ansible.builtin.shell: tar -xzf artifact.tar.gz
  args:
    chdir: /home/ubuntu

- name: "install nodejs 13.8.0"
  become: true
  shell: n 13.8.0

- name: "excuting with pm"
  shell: |
      cd /home/ubuntu/backend/dist
      pm2 stop default
      pm2 startup systemd
      pm2 start npm -- start
      pm2 start main.js
      
- name: "pm2 server start"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu