---
- name: "Copy Backend file"
  copy:
    src: artifact.tar.gz
    dest: /home/ubuntu

- name: "Unarchive file"
  ansible.builtin.shell: tar -xzf artifact.tar.gz
  args:
    chdir: /home/ubuntu
    
- name: "start app" 
  become: yes
  shell: |      
      cd /home/ubuntu/backend/dist
      pm2 stop default
      pm2 startup systemd
      pm2 start npm -- start
      pm2 start main.js

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu